name: SparkyFitness
version: v0.15.8.2
slug: sparkyfitness
description: Sparky Fitness Frontend
arch:
  - aarch64
  - amd64
panel_icon: mdi:weight-lifter
url: "https://github.com/CodeWithCJ/SparkyFitness"
startup: application
boot: auto
init: false
ports:
  80/tcp: 3080
timeout: 30
map: []
legacy: true
options:
  SPARKY_FITNESS_FRONTEND_URL: "homeassistant.local/hassio/ingress/sparkyfitness"
  SPARKY_FITNESS_SERVER_HOST: homeassistant.local
  SPARKY_FITNESS_SERVER_PORT: "3010"
schema:
  SPARKY_FITNESS_FRONTEND_URL: str
  SPARKY_FITNESS_SERVER_HOST: str
  SPARKY_FITNESS_SERVER_PORT: str
image: codewithcj/sparkyfitness
