name: SparkyFitness
version: v0.15.8.2
slug: sparkyfitness
description: Sparky Fitness Frontend
arch:
  - aarch64
  - amd64
panel_icon: mdi:water
url: "https://github.com/CodeWithCJ/SparkyFitness"
startup: application
boot: auto
init: false
ingress: true
timeout: 30
map: []
ports: {}
ports_description: {}
options:
  username: 
  password: 
  mqttUri: ''
  mqttUsername: ''
  mqttPassword: ''
  refreshRate: 5
schema:
  username: str
  password: password
  mqttUri: str?
  mqttUsername: str?
  mqttPassword: password?
  refreshRate: int
image: codewithcj/sparkyfitness
