name: SparkyFitness
version: v0.15.8.2
slug: sparkyfitness
description: Sparky Fitness Frontend
arch:
  - aarch64
  - amd64
panel_icon: mdi:water
url: "https://github.com/CodeWithCJ/SparkyFitness"
startup: application
boot: auto
init: false
ingress_port: 3004
ingress: true
timeout: 30
map: []
legacy: true
options:
  SPARKY_FITNESS_FRONTEND_URL: "homeassistant.local/hassio/ingress/sparkyfitness"
schema:
  SPARKY_FITNESS_FRONTEND_URL: str
image: codewithcj/sparkyfitness
