# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: sparkyfitness-server
version: "v0.15.8"
slug: sparkyfitness-server
description: SparkyFitness Server
url: "https://github.com/CodeWithCJ/SparkyFitness"
arch:
  - aarch64
  - amd64
init: false
image: "codewithcj/sparkyfitness_server:v0.15.8.2"
