# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SparkyFitness Server
version: v0.15.8.2
slug: sparkyfitness-server
description: SparkyFitness Server
url: "https://github.com/CodeWithCJ/SparkyFitness"
arch:
  - aarch64
  - amd64
boot: auto
init: false
ingress: false
timeout: 30
map:
  - type: backup
    read_only: False
    path: /app/SparkyFitnessServer/backup
  - type: data
    read_only: False
    path: /app/SparkyFitnessServer/uploads  
options:
  SPARKY_FITNESS_DB_NAME: "postgres"
  SPARKY_FITNESS_DB_USER: "postgres"
  SPARKY_FITNESS_DB_HOST: "homeassistant.local"
  SPARKY_FITNESS_FRONTEND_URL: "homeassistant.local/hassio/ingress/sparkyfitness"
  SPARKY_FITNESS_APP_DB_USER: "sparky_app"
schema:
  SPARKY_FITNESS_LOG_LEVEL: "str?"
  SPARKY_FITNESS_DB_USER: "str"
  SPARKY_FITNESS_DB_HOST: "str"
  SPARKY_FITNESS_DB_NAME: "str"
  SPARKY_FITNESS_DB_PASSWORD: "str"
  SPARKY_FITNESS_APP_DB_USER: "str"
  SPARKY_FITNESS_APP_DB_PASSWORD: "str"
  SPARKY_FITNESS_DB_PORT: "str?"
  SPARKY_FITNESS_API_ENCRYPTION_KEY: "str"
  JWT_SECRET: "str"
  SPARKY_FITNESS_FRONTEND_URL: "str"
  SPARKY_FITNESS_DISABLE_SIGNUP: "str?"
  SPARKY_FITNESS_ADMIN_EMAIL: "str?"
  SPARKY_FITNESS_EMAIL_HOST: "str?"
  SPARKY_FITNESS_EMAIL_PORT: "str?"
  SPARKY_FITNESS_EMAIL_SECURE: "str?"
  SPARKY_FITNESS_EMAIL_USER: "str?"
  SPARKY_FITNESS_EMAIL_PASS: "str?"
  SPARKY_FITNESS_EMAIL_FROM: "str?"
  GARMIN_MICROSERVICE_URL: "str?"
legacy: true
image: "codewithcj/sparkyfitness_server"
